### ISSUE TITLE
Annotate all sequences with Rfam families

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#143]
**TODO**: add checkboxes with detailed plan

- [ ] show Rfam annotations in a new part of the sequence page
- [ ] show warnings if Rfam annotations indicate contamination (see #66)
- [ ] use Rfam annotations to infer ncRNA type and description
