### ISSUE TITLE
Map sequences to reference genomes

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#145]
- [x] automatically download Ensembl fasta files for all species
    - [x] deal with Ensembl vs Ensembl Genomes assembly differences #375 
- [ ] download hg19 too #69 
- [x] export RNAcentral sequences from all Ensembl species
- [x] run blat
- [x] replace old genome mapping with new ones for each species in the database
- [x] upgrade Genoverse component to show all ensembl species #377 
- [x] resolve Genoverse issues with scaffolds #329 
- [ ] integrate RNAcentral tracks into UCSC and Ensembl genome browsers #178 
- [x] clean up `rnc_coordinates` table (keep only Ensembl and LNCipedia)
- [x] export all sequences that are not in `rnc_coordinates` for genome mapping (currently, only Ensembl sequences are excluded)
- [x] automate selection of example genome locations?

**Comment by blakesweeney** [comment]
- [ ] Map sequences to hg19 as well.
