### ISSUE TITLE
Publications tab improvements

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#199]
- [x] filter publications by taxid - from #251 
- [x] hide `INSDC submission` entries if there are real journal publications available - from #110
- [x] hide long author lists
- [x] prioritise RNA-specific papers over papers describing Expert Databases
- [x] add a tag _Expert Database_ to papers associated with expert database submissions
- [x] add links to EuropePMC
- [x] retrieve missing bibliographic information from EuropePMC (DOI, PubMed IDs etc) - moved to #296
- [x] connect INSDC submissions with corresponding journal articles using EuropePMC API. Sometimes an entry goes to ENA as `INSDC submission` and the journal article is published afterwards - moved to #296
- [x] explore using EBI search index to retrieve publications - moved to #296

Example: http://rnacentral.org/rna/URS000075E952/9606?tab=publications

Time estimate: 2 weeks.
