### ISSUE TITLE
Release 13 checklist

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#466]
## Website

- [ ] Update database statistics (`python manage.py database_stats`)
- [ ] Update wwwdev search index
- [ ] Update Postgres databases
- [ ] Update web VMs
- [ ] Update sequence search fasta files
- [ ] Update FTP archive
- [ ] Update www search index and switch to it

## Outreach

- [ ] Publish blog post
- [ ] Announce on the mailing list
- [ ] Post on Twitter
- [ ] Post an EBI Service news

## Review

- [ ] Close GitHub release project
- [ ] Review GitHub issues
