### ISSUE TITLE
Release 14 checklist

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#472]
## Website

- [x] Update database statistics (`python manage.py database_stats`)
- [x] Update wwwdev search index
- [x] Update Postgres web databases
- [ ] Update public Postgres database
- [x] Vacuum analyse full
- [x] Update web VMs
- [x] Update sequence search fasta files
- [x] Update text search export files
- [x] Update FTP archive
- [x] Update www search index and switch to it
- [x] Update example genome locations and import karyotypes
- [x] Update About Us page (timeline and database growth charts)
- [x] Update RELEASE_ANNOUNCEMENT_URL
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Add release graphic

## Outreach

- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter
- [x] Post an EBI Service news

## Review

- [x] Close GitHub release project
- [x] Review GitHub issues
- [x] Sync PRO, DEV, and TEST databases
- [x] Submit sitemap to Google

**Comment by AntonPetrov** [comment]
- [ ] deal with new ENA metagenomic rRNAs
- [ ] check `should_show` logic for LSUs
- [ ] fix quotes in descriptions
- [ ] list MalaCards diseases

**Comment by blakesweeney** [comment]
- [ ] Store disease information from malacards
- [ ] Export disease information into search index
- [ ] Update search team with new field
- [ ] Precompute and ensure genecards/malacards are in database fields
- [ ] Assign rRNA fragments to metagenome fragments
- [ ] Exclude rRNA fragments from search index

**Comment by blakesweeney** [comment]
- [ ] Exclude rRNA fragments from sequence search files

**Comment by blakesweeney** [comment]
- [ ] Validate fixes to MirGeneDB coordinate import

**Comment by blakesweeney** [comment]
- [ ] Strip leading `b"` and trailing `"` from descriptions

**Comment by blakesweeney** [comment]
- [ ] Rerun mirgenedb import with fixed coordinates

**Comment by blakesweeney** [comment]
- [ ] Validate that incorrect QA warnings for 5SrRNAdb sequences are not shown

**Comment by blakesweeney** [comment]
- [ ] Fix the short_description field in precompute
