### ISSUE TITLE
Release 15 checklist

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#491]
## Website

- [x] Update database statistics (`python manage.py database_stats`)
- [x] Update wwwdev search index
- [x] Update Postgres web databases
- [x] Update public Postgres database
- [x] Vacuum analyse full
- [x] Update web VMs
- [x] Update sequence search fasta files
- [x] Update text search export files
- [x] Update FTP archive
- [x] Update www search index and switch to it
- [x] Update example genome locations and import karyotypes
- [x] Update About Us page (timeline and database growth charts)
- [x] Update RELEASE_ANNOUNCEMENT_URL
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Add release graphic

## Outreach

- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter
- [ ] Post an EBI Service news

## Review

- [x] Close GitHub release project
- [ ] Review GitHub issues
- [x] Sync PRO, DEV, and TEST databases
- [ ] Submit sitemap to Google
- [ ] Review documentation (RNAcentral Help and Train Online)
