### ISSUE TITLE
Release 16 checklist

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-webcode#505]
## Website

- [x] Update wwwdev search index
- [x] Update database statistics (`python manage.py database_stats`)
- [x] Update example genome locations and import karyotypes
- [x] Update About Us page (timeline and database growth charts)
- [x] Update RELEASE_ANNOUNCEMENT_URL
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Add release graphic
- [x] Vacuum analyse full
- [x] Update Postgres web databases
- [x] Update web VMs
- [x] Update public Postgres database
- [x] Update sequence search fasta files
- [x] Update text search export files
- [x] Update FTP archive
- [x] Update www search index and switch to it
## Outreach

- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter
- [x] Post an EBI Service news

## Review

- [x] Close GitHub release project
- [x] Review GitHub issues
- [ ] Sync PRO, DEV, and TEST databases
- [x] Submit sitemap to Google
- [x] Review documentation (RNAcentral Help and Train Online)
