### ISSUE TITLE
Release 18 Checklist

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#538]
## Website

- [x] Update wwwdev search index
- [x] Update database statistics (`python manage.py database_stats`)
- [x] Update example genome locations and import karyotypes
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Vacuum analyse full
- [x] Update Postgres web databases
- [x] Update web VMs
- [x] Update public Postgres database
- [x] Update text search export files
- [x] Update FTP archive
- [x] Update www search index and switch to it
- [x] Add release graphic @AntonPetrov 
- [x] Update sequence search fasta files in TEST @carlosribas
- [x] Update sequence search fasta files in PROD (after the release) @carlosribas 
- [x] Update release number in website header @carlosribas
- [x] Update release number in sequence search results metadata file @carlosribas 
- [x] Update About Us page (timeline and database growth charts) @carlosribas 
- [x] Update RELEASE_ANNOUNCEMENT_URL @carlosribas 

## Outreach

- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter

## Review

- [x] Close GitHub release project
- [ ] Review GitHub issues
- [x] Sync PRO, DEV, and TEST databases
- [x] Submit sitemap to Google
- [x] Review documentation (RNAcentral Help and Train Online)
- [ ] Create release checklist for the next release
