### ISSUE TITLE
Release 19 Checklist

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#548]
## Pre Announce

- [x] Update wwwdev search index
- [x] Update database statistics (`python manage.py database_stats`)
- [x] Update example genome locations and import karyotypes
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Vacuum analyse full
- [x] Update Postgres web databases
- [x] Update web VMs
- [x] Update public Postgres database
- [x] Update text search export files
- [x] Create and populate `.release` FTP directory
- [x] Move`.release` FTP directory to `release`
- [x] Update `current_release` FTP symlink
- [x] Add release graphic 
- [x] Update sequence search fasta files in TEST
- [x] Update sequence search fasta files in PROD 
- [x] Update release number in website header 
- [x] Update release number in sequence search results metadata file
- [x] Update About Us page (timeline and database growth charts) 
- [x] Update RELEASE_ANNOUNCEMENT_URL 

## Announce

- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter
- [x] Backup old text-search files
- [x] Copy dev-nightly search files to nightly

## Post Announce
- [x] Switch to nightly text search index
- [x] Close GitHub release project
- [x] Review GitHub issues
- [x] Sync PRO, DEV, and TEST databases
- [x] Submit sitemap to Google
- [x] Review documentation (RNAcentral Help and Train Online)
- [x] Create release checklist for the next release
