### ISSUE TITLE
Release 22 Checklist

### ISSUE THREAD

**Issue by carlosribas** [RNAcentral/rnacentral-webcode#603]
## Testing

- [x] Update wwwdev search index
- [x] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [x] Update test website
- [x] Update text search export files
- [x] Create and populate `.release` FTP directory
- [x] Add release graphic 
- [x] Update release number in website header 
- [x] Update About Us page (timeline and database growth charts) 
- [x] Update RELEASE_ANNOUNCEMENT_URL 
- [x] Update sequence search fasta files in TEST
- [x] Update release number in sequence search results metadata file

## Pre Announce (silent release)

- [x] Update Postgres web databases (HH and FB)
- [x] Update public Postgres database
- [x] Copy postgres dump into FTP
- [x] Update web VMs
- [x] Update sequence search fasta files in PROD
- [x] Update release number in sequence search results metadata file in PROD
- [x] Move`.release` FTP directory to `release`
- [x] Update sitemap

## Announce

- [x] Update `current_release` FTP symlink
- [x] Publish blog post
- [x] Announce on the mailing list
- [x] Post on Twitter
- [x] Backup old text-search files
- [x] Copy dev-nightly search files to nightly (except genes_* files)

## Post Announce
- [x] Merge release-22 into master
- [x] Switch to nightly text search index
- [x] Close GitHub release project
- [x] Review GitHub issues
- [x] Sync PRO, DEV, and TEST databases
- [x] Review documentation (RNAcentral Help and Train Online)
- [x] Create release checklist for the next release
