### ISSUE TITLE
Tracking issue for databases to import

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-webcode#608]
This issue is to track databases which could be good to import. We should review this issue each release to pick new databases. Additionally, whenever and interesting database is found it should be put into this list. 

Once a database is chosen issues for that particular database for importing and how to best display the data should be created.

-  [ ] MitoFun (https://github.com/RNAcentral/rnacentral-webcode/issues/496)
  Currently RNAcentral does not have a very good collection of fungal mito RNAs but we could obtain them from the following   resource:
http://mitofun.biol.uoa.gr/download.html
http://mitofun.biol.uoa.gr/fasta/gGENE.fasta.zip
- [ ] RMDB: https://rmdb.stanford.edu/tools/ (https://github.com/RNAcentral/rnacentral-webcode/issues/138)
  In order to establish links with RMDB, we need to specify how a canonical sequence in RNAcentral ‘maps on’ to the sequence in RMDB. So far we haven't done any imports based on sequence mapping, but we will implement this approach for importing Rfam predictions. Once this is done, we can use the same procedure for RMDB.
- [ ] FunPEP (https://github.com/RNAcentral/rnacentral-webcode/issues/531)
  A new database of experimentally confirmed peptides found within lncRNAs: https://www.mdpi.com/2311-553X/6/4/41/htm
- [ ] lncDB (https://github.com/RNAcentral/rnacentral-webcode/issues/238)
  This database (http://www.bio-bigdata.com/Ubetis-LncDB/ I think) is a very high quality lncRNA database. We should treat data from it as being very reliable, according to John.
- [ ] OMIM (https://github.com/RNAcentral/rnacentral-webcode/issues/214)
  OMIM database links to Ensembl and HGNC which are already in RNAcentral so it should be possible to integrate with OMIM:
http://www.omim.org/entry/614625?search=dancr
- [ ] LncRNAWiki (https://github.com/RNAcentral/rnacentral-webcode/issues/203)
  Example page: http://lncrna.big.ac.cn/index.php/ENST00000526269.2
- [ ] r-bind 
  A database of molecules to bind to RNA, other than the ribosome. This could be very useful if we move toward more pharma work. Importing it might be adding annotations to specific sequences or maybe into Rfam families.  https://rbind.chem.duke.edu/
