### ISSUE TITLE
Release 24 Checklist

### ISSUE THREAD

**Issue by carlosribas** [RNAcentral/rnacentral-webcode#624]
## Testing

- [ ] Update wwwdev search index
- [ ] Update database versions in `config/expert_databases.py` - especially FlyBase and Ensembl
- [ ] Update test website
- [ ] Update text search export files
- [ ] Create and populate `.release` FTP directory
- [ ] Add release graphic 
- [ ] Update release number in website header 
- [ ] Update About Us page (timeline and database growth charts) 
- [ ] Update RELEASE_ANNOUNCEMENT_URL 
- [ ] Update sequence search fasta files in TEST
- [ ] Update release number in sequence search results metadata file
- [ ] Update the fasta file stored in PVC - HX cluster (rnacentral_species_specific_ids)

## Pre Announce (silent release)

- [ ] Update Postgres web databases (HH and FB)
- [ ] Update public Postgres database
- [ ] Copy postgres dump into FTP
- [ ] Update web VMs
- [ ] Update the fasta file stored in PVC - HH cluster (rnacentral_species_specific_ids)
- [ ] Update sequence search fasta files in PROD
- [ ] Update release number in sequence search results metadata file in PROD
- [ ] Move`.release` FTP directory to `release`
- [ ] Update sitemap

## Announce

- [ ] Update `current_release` FTP symlink
- [ ] Publish blog post
- [ ] Announce on the mailing list
- [ ] Post on Twitter
- [ ] Backup old text-search files
- [ ] Copy dev-nightly search files to nightly (except genes_* files)

## Post Announce
- [ ] Merge release-24 into master
- [ ] Switch to nightly text search index
- [ ] Review GitHub issues
- [ ] Sync PRO, DEV, and TEST databases
- [ ] Review documentation (RNAcentral Help and Train Online)
- [ ] Create release checklist for the next release
- [ ] Update sequence search on GCP
- [ ] Close GitHub release project

**Comment by carlosribas** [comment]
This is now done in Linear
